#! /bin/bash
cp -f Makefile_Simple Makefile 
g++  -M                 \
	ConfFileRead.cpp	\
	BasicConfigure.cpp	\
	Connection.cpp		\
	CommandHandle.cpp	\
	CommandQuene.cpp	\
	Communication.cpp	\
	Predicate.cpp	\
	Matrix.cpp	\
	Geometry.cpp	\
	WorldModel.cpp	\
	WorldModelInit.cpp	\
	WorldModelUpdate.cpp	\
	WorldModelParse.cpp	\
	Situation.cpp	\
	SitUnitSquare.cpp	\
	SitDribble.cpp	\
	SitKick.cpp		\
	SitPass.cpp		\
	SitRun.cpp		\
	Formation.cpp	\
	Attitude.cpp	\
	Logger.cpp		\
	Timer.cpp		\
	JointControl.cpp	\
	Action.cpp		\
	ActionTurn.cpp	\
	ActionTrans.cpp	\
	HumanoidControl.cpp	\
	Dribble.cpp		\
	Kick.cpp		\
	Motion.cpp		\
	MotionGoto.cpp	\
	SmartGoto.cpp	\
	MotionDribble.cpp	\
	MotionKick.cpp	\
	MotionPass.cpp	\
	HumanGoto.cpp	\
	Obstacle.cpp	\
	HandleBall.cpp	\
	RunPosition.cpp	\
	Brain.cpp		\
	BrainGoalie.cpp	\
	BrainNormal.cpp	\
	coach.cpp		\
	Vision.cpp		\
	Hear.cpp		\
	Say.cpp			\
	AgentInfo.cpp	\
	Agent.cpp	\
	main.cpp			\
	>> Makefile
